{% set version = "0.6.1.1" %}

package:
  name: spam
  version: {{ version }}

source:
  url: https://gricad-gitlab.univ-grenoble-alpes.fr/ttk/spam/-/archive/version-{{ version }}/spam-version-{{ version }}.tar.gz
  sha256: ec932d3a140ef4fcd7072627ba83c7c03be1bac1e9c94c53d25ceca7d6717432

build:
  number: 1

requirements:
  build:
    - python
    - numpy
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - pybind11
    - pybind11-abi
    - eigen
    - cgal-cpp
    - gmp                                    # [unix]
    - m2w64-gmp                              # [win]
    - pyamg
  host:
    - python
    - pip
    - numpy
    - pybind11
    - eigen
    - cgal-cpp
    - gmp                                    # [unix]
    - m2w64-gmp                              # [win]
  run:
    - python
    - matplotlib-base
    - gmp                                    # [unix]
    - mpir                                   # [win]
    - r-base
    - numpy
    - scipy
    - scikit-image
    - tifffile
    - matplotlib-base
    - SimpleITK
    - progressbar
    - python-decouple
    - gmsh
    - meshio =4.3.13
    - h5py

test:
  imports:
    - spam.DIC
    - spam.helpers
  requires:
    - meshio <=4.3.13,>=4.3.0
  commands:
    - spam-ldic -h

about:
  home: https://ttk.gricad-pages.univ-grenoble-alpes.fr/spam/intro.html
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.md
  summary: "Software for Practical Analysis of Materials"
  doc_url: https://ttk.gricad-pages.univ-grenoble-alpes.fr/spam/intro.html
  dev_url: https://gricad-gitlab.univ-grenoble-alpes.fr/ttk/spam/-/tree/master

extra:
  recipe-maintainers:
    - edwardando
    - stamatio
